import './load-env';
import { NestFactory } from '@nestjs/core';
import { ValidationPipe } from '@nestjs/common';
import * as dns from 'dns';
import * as express from 'express';
import * as path from 'path';
import { AppModule } from './app.module';

// Prefer IPv4 on Windows when resolving hostnames (pairs with https.Agent family:4 in WebsiteService for v0 API).
if (process.platform === 'win32' && process.env.V0_DNS_IPV4_FIRST !== '0') {
  dns.setDefaultResultOrder('ipv4first');
}

async function bootstrap() {
  const app = await NestFactory.create(AppModule, { bodyParser: false });
  
  // Enable CORS
  const allowedOrigins = (process.env.FRONTEND_URL || 'http://localhost:5173')
    .split(',')
    .map((origin) => origin.trim().replace(/\/+$/, ''))
    .filter(Boolean);
  app.enableCors({
    origin: (origin, callback) => {
      if (!origin || allowedOrigins.includes(origin.replace(/\/+$/, ''))) return callback(null, true);
      return callback(new Error('Origin is not allowed by CORS'));
    },
    credentials: true,
  });

  const jsonBodyLimit = process.env.HTTP_JSON_BODY_LIMIT || '30mb';
  app.use(express.json({ limit: jsonBodyLimit }));
  app.use(express.urlencoded({ extended: true, limit: jsonBodyLimit }));

  // React preview artifacts served as static files (generated by the local build worker).
  app.use('/preview-artifacts', express.static(path.join(process.cwd(), '.preview-artifacts')));

  // Global validation pipe
  app.useGlobalPipes(
    new ValidationPipe({
      whitelist: true,
      forbidNonWhitelisted: true,
      transform: true,
    }),
  );

  const port = process.env.PORT || 3000;
  await app.listen(port, '0.0.0.0');
  // v0 generation/edit can exceed 5m (polling + long sync); keep sockets open (default 900s, override with HTTP_SERVER_TIMEOUT_MS).
  const serverTimeoutMs = Number(process.env.HTTP_SERVER_TIMEOUT_MS) || 900_000;
  app.getHttpServer().setTimeout(serverTimeoutMs);
  console.log(`🚀 WebGenius API is running on: http://localhost:${port}`);
}

bootstrap();
