import { Injectable, Logger } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { ObjectId } from 'mongodb';
import { Website } from '../entities/website.entity';
import { WebsiteService } from '../website/website.service';
import { BlueprintPromptService } from './blueprint-prompt.service';
import { OpenAIBackendService } from './openai-backend.service';
import { ProjectMergerService } from './project-merger.service';
import { BackendRuntimeService } from './backend-runtime.service';
import { FullStackGenerationMode } from './dto/generate-fullstack.dto';
import { AppPlannerService } from './app-planner.service';
import { BackendBuilderService } from './backend-builder.service';
import { FrontendBuilderService } from './frontend-builder.service';
import { FullStackPlan } from './fullstack.types';

@Injectable()
export class FullStackCoordinatorService {
  private readonly logger = new Logger(FullStackCoordinatorService.name);

  constructor(
    private readonly openAIBackend: OpenAIBackendService,
    private readonly blueprintPrompt: BlueprintPromptService,
    private readonly projectMerger: ProjectMergerService,
    private readonly websiteService: WebsiteService,
    private readonly backendRuntime: BackendRuntimeService,
    private readonly appPlanner: AppPlannerService,
    private readonly backendBuilder: BackendBuilderService,
    private readonly frontendBuilder: FrontendBuilderService,
    @InjectRepository(Website) private readonly websiteRepository: Repository<Website>,
  ) {}

  async generate(userId: string, prompt: string, requestedName?: string, mode: FullStackGenerationMode = 'production-app'): Promise<Website> {
    const websiteName = requestedName?.trim() || `Full-stack app ${Date.now()}`;

    this.logger.log(`Starting full-stack generation for user ${userId}, project "${websiteName}", mode "${mode}"`);
    try {
      const backendPlan = await this.createBackendPlan(prompt, websiteName, mode);
      this.logger.log(`Backend plan ready for "${websiteName}" with ${backendPlan.backendFiles.length} files`);
      const isProductionMode = mode === 'production-app' || mode === 'production-crm';
      const frontendPrompt = isProductionMode
        ? this.blueprintPrompt.createMinimalV0FrontendPrompt(prompt, backendPlan.blueprint)
        : this.blueprintPrompt.createFrontendPrompt(prompt, backendPlan.blueprint);
      const project = this.projectMerger.merge(backendPlan, frontendPrompt);

      if (isProductionMode && process.env.FULLSTACK_USE_LOCAL_FRONTEND_BUILDER === 'true') {
        this.logger.warn(
          `Using disabled dev fallback local frontend builder for "${websiteName}" because FULLSTACK_USE_LOCAL_FRONTEND_BUILDER=true`,
        );
        const frontend = this.frontendBuilder.buildContractFrontend(project.blueprint);
        const website = this.websiteRepository.create({
          userId,
          websiteName,
          framework: 'react',
          prompt,
          htmlCode: '',
          cssCode: '',
          jsCode: '',
          components: frontend.components,
          viteConfig: frontend.viteConfig,
          fullStackBlueprint: project.blueprint,
          backendFiles: project.backendFiles,
          backendStatus: backendPlan.backendStatus || 'generated',
          backendLogs: backendPlan.backendLogs || 'Production app backend generated by WebGenius.',
          backendPreviewUrl: backendPlan.backendPreviewUrl,
          reactBuildStatus: 'queued',
        } as Partial<Website>);
        const saved = await this.websiteRepository.save(website);
        await this.websiteService.rebuildReactPreview(saved.id.toString(), userId);
        return this.backendRuntime.start(saved.id.toString(), userId);
      }

      const generated = await this.websiteService.generateWebsite(
        userId,
        project.frontendPrompt,
        websiteName,
        'react',
        undefined,
        prompt,
        undefined,
        false,
        isProductionMode
          ? {
              systemPromptOverride: this.blueprintPrompt.createMinimalV0SystemPrompt(),
              userPromptOverride: project.frontendPrompt,
              maxAttempts: 1,
              retryWithSync: false,
              promptLengthWarningChars: 4000,
              promptLengthHardLimitChars: 5000,
              label: 'fullstack-production-v0',
            }
          : undefined,
      );

      const generatedId = generated.id.toString();
      const website = await this.websiteRepository.findOne({
        where: { _id: new ObjectId(generatedId) } as any,
      });
      if (!website) throw new Error('Generated website could not be reloaded for full-stack merge');
      website.prompt = prompt;
      website.fullStackBlueprint = project.blueprint;
      website.backendFiles = project.backendFiles;
      website.backendStatus = backendPlan.backendStatus || 'generated';
      website.backendLogs = backendPlan.backendLogs || 'Backend generated by OpenAI.';
      website.backendPreviewUrl = backendPlan.backendPreviewUrl;
      const saved = await this.websiteRepository.save(website);
      // The original React build can be queued before backend files are attached. Queue a fresh build so the
      // R2 artifact receives its project-specific Render API gateway configuration.
      await this.websiteService.rebuildReactPreview(saved.id.toString(), userId);
      if (backendPlan.runtimeId) return saved;
      return this.backendRuntime.start(saved.id.toString(), userId);
    } catch (error: any) {
      this.logger.error(
        `Full-stack generation failed for user ${userId}, project "${websiteName}": ${error?.message || String(error)}`,
        error?.stack,
      );
      throw error;
    }
  }

  private async createBackendPlan(prompt: string, websiteName: string, mode: FullStackGenerationMode): Promise<FullStackPlan> {
    if (mode === 'production-crm') {
      const blueprint = this.appPlanner.createProductionCrmBlueprint(prompt, websiteName);
      const backendFiles = this.backendBuilder.buildProductionCrmBackend(blueprint);
      return {
        blueprint,
        backendFiles,
        backendStatus: 'generated',
        backendLogs: 'Production CRM backend generated by WebGenius V2 planner.',
      };
    }
    if (mode === 'production-app') {
      return this.openAIBackend.generateDirect(prompt, websiteName);
    }
    // OpenAI owns the shared contract and small Node backend. v0 receives only the derived UI task.
    return this.openAIBackend.generate(prompt, websiteName);
  }
}
