import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { ObjectId } from 'mongodb';
import { Website } from '../entities/website.entity';
import { WebsiteService } from '../website/website.service';
import { BlueprintPromptService } from './blueprint-prompt.service';
import { OpenAIBackendService } from './openai-backend.service';
import { ProjectMergerService } from './project-merger.service';
import { BackendRuntimeService } from './backend-runtime.service';

@Injectable()
export class FullStackCoordinatorService {
  constructor(
    private readonly openAIBackend: OpenAIBackendService,
    private readonly blueprintPrompt: BlueprintPromptService,
    private readonly projectMerger: ProjectMergerService,
    private readonly websiteService: WebsiteService,
    private readonly backendRuntime: BackendRuntimeService,
    @InjectRepository(Website) private readonly websiteRepository: Repository<Website>,
  ) {}

  async generate(userId: string, prompt: string, requestedName?: string): Promise<Website> {
    const websiteName = requestedName?.trim() || `Full-stack app ${Date.now()}`;

    // OpenAI owns the shared contract and small Node backend. v0 receives only the derived UI task.
    const backendPlan = await this.openAIBackend.generate(prompt, websiteName);
    const frontendPrompt = this.blueprintPrompt.createFrontendPrompt(prompt, backendPlan.blueprint);
    const project = this.projectMerger.merge(backendPlan, frontendPrompt);

    const generated = await this.websiteService.generateWebsite(
      userId,
      project.frontendPrompt,
      websiteName,
      'react',
      undefined,
      prompt,
    );

    const generatedId = generated.id.toString();
    const website = await this.websiteRepository.findOne({
      where: { _id: new ObjectId(generatedId) } as any,
    });
    if (!website) throw new Error('Generated website could not be reloaded for full-stack merge');
    website.prompt = prompt;
    website.fullStackBlueprint = project.blueprint;
    website.backendFiles = project.backendFiles;
    website.backendStatus = 'generated';
    website.backendLogs = 'Backend generated by OpenAI. Runtime has not been started yet.';
    const saved = await this.websiteRepository.save(website);
    // The original React build can be queued before backend files are attached. Queue a fresh build so the
    // R2 artifact receives its project-specific Render API gateway configuration.
    await this.websiteService.rebuildReactPreview(saved.id.toString(), userId);
    return this.backendRuntime.start(saved.id.toString(), userId);
  }
}
